import LoanApplication from '../models/LoanApplication.js';
import VerificationTask from '../models/VerificationTask.js';
import AiActivityLog from '../models/AiActivityLog.js';
import Notification from '../models/Notification.js';
import { analyzeLoanApplication } from '../services/geminiService.js';

const normalizePan = (value) => String(value || '').replace(/\s/g, '').toUpperCase();
const normalizeAadhaar = (value) => String(value || '').replace(/\D/g, '');

const PAN_REGEX = /^[A-Z]{5}[0-9]{4}[A-Z]$/;

export const createApplication = async (req, res) => {
  const { customerName, panNumber, aadhaarNumber, income, loanAmount, documents } = req.body;
  const pan = normalizePan(panNumber);
  const aadhaar = normalizeAadhaar(aadhaarNumber);
  const trimmedName = String(customerName || '').trim();

  if (!trimmedName) {
    return res.status(400).json({ message: 'Applicant name is required' });
  }
  if (!PAN_REGEX.test(pan)) {
    return res.status(400).json({ message: 'Invalid PAN format (expected e.g. ABCDE1234F)' });
  }
  if (aadhaar.length !== 12) {
    return res.status(400).json({ message: 'Aadhaar must be exactly 12 digits' });
  }

  const inc = Number(income);
  const loan = Number(loanAmount);
  if (!Number.isFinite(inc) || inc <= 0) {
    return res.status(400).json({ message: 'Valid annual income is required' });
  }
  if (!Number.isFinite(loan) || loan <= 0) {
    return res.status(400).json({ message: 'Valid loan amount is required' });
  }

  const referenceId = `APP-${String(Date.now()).slice(-6)}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`;

  const application = await LoanApplication.create({
    referenceId,
    customerName: trimmedName,
    panNumber: pan,
    aadhaarNumber: aadhaar,
    income: inc,
    loanAmount: loan,
    documents: Array.isArray(documents) ? documents : [],
    createdBy: req.user.id,
    status: 'identity_verification',
    workflow: [
      { step: 'Application Submitted', date: new Date(), actor: req.user.name || 'User' },
      { step: 'Identity verification started', date: new Date(), actor: 'FINOVA AI' },
    ],
  });

  const aiAnalysis = await analyzeLoanApplication(application.toObject());
  let decision = String(aiAnalysis.suggestedDecision || 'review').toLowerCase().trim();
  if (!['approve', 'reject', 'review'].includes(decision)) decision = 'review';

  application.riskScore = aiAnalysis.riskScore;
  application.fraudProbability = aiAnalysis.fraudProbability || 0;
  application.approvalProbability = aiAnalysis.approvalProbability || 0;
  application.repaymentConfidence = aiAnalysis.repaymentConfidence || 0;
  application.workflowPriority = aiAnalysis.workflowPriority || 'Medium';
  application.suggestedDecision = decision;
  application.riskSummary = aiAnalysis.riskSummary;
  application.missingDocuments = aiAnalysis.missingDocuments || [];
  application.workflow.push({ step: 'AI Risk Assessment Completed', date: new Date(), actor: 'FINOVA AI' });

  const riskStage = aiAnalysis.riskScore >= 80 ? 'fraud_detection' : aiAnalysis.riskScore >= 65 ? 'ai_risk_analysis' : 'ai_risk_analysis';
  application.status = riskStage;
  application.workflow.push({ step: `${riskStage.replace(/_/g, ' ')}`, date: new Date(), actor: 'FINOVA AI' });

  if (aiAnalysis.fraudProbability >= 65) {
    application.status = 'fraud_detection';
    application.workflow.push({ step: 'Fraud detection triggered', date: new Date(), actor: 'FINOVA AI' });
  }

  if (decision === 'approve' && aiAnalysis.approvalProbability >= 75 && aiAnalysis.fraudProbability < 40) {
    application.status = 'under_review';
    application.workflow.push({ step: 'Approval review queued', date: new Date(), actor: 'FINOVA AI' });
  }

  if (application.status === 'identity_verification' || application.status === 'ai_risk_analysis' || application.status === 'fraud_detection') {
    application.assignedOfficer = req.user.id;
    await VerificationTask.create({
      applicationId: application._id,
      officer: req.user.id,
      status: 'pending',
      notes: 'Generated by FINOVA AI for verification review.',
      timeline: [
        { date: new Date(), event: 'Task created', detail: 'AI generated a verification queue task.' },
      ],
    });
  }

  await application.save();

  await Notification.create({
    applicationId: application._id,
    type: 'application',
    title: 'New loan application received',
    detail: `Application ${application.referenceId} has been captured and queued for AI review.`,
    severity: 'info',
  });

  await AiActivityLog.create({
    applicationId: application._id,
    type: 'analysis',
    title: 'AI analysis completed',
    detail: `Risk: ${application.riskScore}, fraud: ${application.fraudProbability}%, approval: ${application.approvalProbability}%. ${application.riskSummary}`,
    severity: application.riskScore > 70 ? 'warning' : 'info',
  });

  res.status(201).json(application);
};

export const getApplications = async (req, res) => {
  const applications = await LoanApplication.find().sort({ createdAt: -1 }).limit(200).lean();
  res.json(applications);
};

export const getApplicationById = async (req, res) => {
  const application = await LoanApplication.findById(req.params.id).lean();
  if (!application) return res.status(404).json({ message: 'Application not found' });
  const logs = await AiActivityLog.find({ applicationId: application._id }).sort({ timestamp: -1 }).lean();
  res.json({ ...application, logs });
};

export const assignOfficer = async (req, res) => {
  const { officerId, notes } = req.body;
  const application = await LoanApplication.findById(req.params.id);
  if (!application) return res.status(404).json({ message: 'Application not found' });

  const assigned = officerId || req.user.id;
  application.assignedOfficer = assigned;
  application.status = 'assigned';
  application.workflow.push({ step: 'Field Verification Assigned', date: new Date(), actor: req.user.name });
  await application.save();

  await VerificationTask.create({
    applicationId: application._id,
    officer: assigned,
    notes,
    timeline: [{ date: new Date(), event: 'Assigned verification officer', detail: notes || 'Auto-assigned by FINOVA' }],
  });

  await Notification.create({
    applicationId: application._id,
    type: 'workflow',
    title: 'Verification officer assigned',
    detail: `Officer assigned to application ${application.referenceId || application._id}.`,
    severity: 'info',
  });

  await AiActivityLog.create({
    applicationId: application._id,
    type: 'task',
    title: 'Verification Officer Assigned',
    detail: `Officer assigned to review the application.`,
    severity: 'info',
  });

  res.json(application);
};
